# Generated by Django 4.1.4 on 2023-01-08 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_date",
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
    ]
